### ISSUE TITLE
feature request: generics support

### ISSUE THREAD

**Issue by Easyoakland** [mcmah309/error_set#15]
Thanks for the crate! I was skeptical before trying, but now I think I won't be using `thiserror` again.

It appears `error_set!` doesn't support generics.
e.g.

```rs
error_set::error_set! {
    Error<E> = {
        Error1,
        Error2,
        Other(E)
    };
}
```
would this be possible to add?

**Comment by mcmah309** [comment]
Of course!

Yes definitely possible. Shouldn't be too difficult either. `where` clauses should be supported as well.

**Comment by mcmah309** [comment]
On master, some edge cases currently. See https://github.com/mcmah309/error_set/issues/18

Release coming later today
