### ISSUE TITLE
feature request: inferred error variants.

### ISSUE THREAD

**Issue by dan-da** [mcmah309/error_set#2]
A cool thing about zig error-sets is that error variants can be defined implicitly "on the fly" in the code. example:

```
pub fn add_inferred(comptime T: type, a: T, b: T) !T {
    const ov = @addWithOverflow(a, b);
    if (ov[1] != 0) return error.Overflow;
    return ov[0];
}
```

here "OverFlow" has never been defined elsewhere. It just came to exist when actually returning it in the fn.

Are there any plans for error-set to do something like this? Perhaps the rust macro system is not flexible enough....?

reference:  https://ziglang.org/documentation/master/#Inferred-Error-Sets

**Comment by mcmah309** [comment]
I didn't know about that. That's cool.

What would be a use case of that? Also if I define `error.Overflow` in another function are they equal?

My understanding of zig-error sets is that they are backed by u16. If I had to guess, every instance of `error.Overflow` is compiled to the same u16, so maybe it didn't just come into existence.

Macros are fairly limited in what they can see. Right now, all the "error_set!" values need to be in the same set. It does not work between sets. I may add an extension to `build.rs` in the future to get around this this limitation. But then it becomes a code generator, which I'm not sure if people would like as much. Right now the approach is to keep all errors in a single set in an `errors.rs` file.

**Comment by dan-da** [comment]
yeah, check out this article which talks more about the implicit behavior.

https://www.aolium.com/karlseguin/4013ac14-2457-479b-e59b-e603c04673c8

It's kind of magical.  perhaps too magical for rust. 

For me, I like the zig implicit thing, but I'd also like to be able to attach a descriptive formatted string, something like:

```
fn divide(dividend: u32, divisor: u32) !u32 {
  if (divisor == 0) {
    return error_set!(DivideByZero, "divide by zero.  {dividend}/0")
  }
  return dividend / divisor;
}
```

I think people want a simple crate they can "cargo add".  I'm unsure if the build.rs mods you are mentioning would change that or not.

**Comment by mcmah309** [comment]
Yeah, adding something to build.rs may cause a host quality of life issues. Such as extra set up, as you mentioned, and forcing the developer to run `cargo build` a lot. Ultimately, even if you did define your errors throughout your code base, build.rs would still probably have to write them all to a single file.

All in all, I sort of prefer the single error file approach anyway. I think with zig, having error types all over the place can become less manageable. Plus in Rust, doing somthing like `crate::errors::` is nice because it will auto-complete with all the types of errors.

**Comment by dan-da** [comment]
It would actually surprise me if this feature request is even possible to do in rust in any kind of ergonomic way.  ;-)

But I had to ask, since the above-linked article was my first introduction to zig error-sets and the inferred error variants seems like the compelling feature, in terms of "wow that's so easy".

feel free to close.

**Comment by mcmah309** [comment]
Okay feel free to re-open if an idea comes up!

**Comment by mcmah309** [comment]
Related to: https://github.com/mcmah309/error_set/issues/17
