### ISSUE TITLE
Doesn't compile with rust < 1.81

### ISSUE THREAD

**Issue by lanastara** [mcmah309/error_set#6]
Version 0.6 throws an error when compiling with rust 1.80 or lower (seems to be the no_std cange since the error trait was only stabilized in core with 1.81)
It would be nice if this was documented somewhere maybe set 1.81 as minimum rust version in cargo.toml.

**Comment by mcmah309** [comment]
Thanks for pointing this out. I added `rust-version` to the cargo file so compilations should get a better error message now. The newest version, `0.6.2`, has this. Version `0.5.*` does not require rust version `1.81`.
