### ISSUE TITLE
[Feature Request] Allow adding `#[display()]` to wrapped error

### ISSUE THREAD

**Issue by duskmoon314** [mcmah309/error_set#7]
## Problem

Only inline variants are currently supported for adding the `#[display()]` attribute. That is, the following code cannot be compiled:

```rust
error_set! {
    FooError = {
        #[display("bar")]
        Bar,
        #[display("baz {x}")]
        Baz{ x: usize },
        #[display("io error: {0}")]
        Io(std::io::Error)
    };
}
```

```console
error: cannot find attribute `display` in this scope
 --> src/lib.rs:9:11
  |
9 |         #[display("io error: {0}")]
  |           ^^^^^^^
```

And if we delete the attribute, we can only get `FooError::Io` as the result of the Display method.

## Proposal

1. Allow adding `#[display()]` to wrapped error.
2. Allow forwarding the Display method.

### Expected usages

Like `thiserror`, we can customize the display messages for wrapped errors:

- `Io(std::io::Error)` will get `FooError::Io` as before.
- `#[display("io error")] Io(std::io::Error)` will get `io error`.
- `#[display("io error: {0}")] Io(std::io::Error)` will get `io error: <display of std::io::Error>`

We could also add `#[display(transparent)]` to forward the entire display method.

**Comment by mcmah309** [comment]
I think this is a good improvement.

For `#[display(transparent)]`, I actually think the opposite might be better. Most error types already implement display and most of the time the developer will want to just forward the message if no display is provided. Thus maybe we should change the default to do this forwarding and go with `#[display(opaque)]` for the edge case where the developer does not want the display to be forwarded and also does not want a custom error message.

**Comment by mcmah309** [comment]
This feature is now on master. As well as the improvements mentioned in my comment above and here https://github.com/mcmah309/error_set/pull/8#issuecomment-2419690969 . Docs have been updated as well.

Feel free to let me know your thoughts on the current DSL, otherwise I will release a new version later tonight. :+1:

**Comment by duskmoon314** [comment]
Thanks for your quick response.

The current DSL meets my needs, and I don't have any more issues. This issue can be closed.
